<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.5</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.bloodbank</groupId>
	<artifactId>blood-bank-services</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>Blood Bank Services Aggregator</name>
	<description>Parent pom for Blood Bank microservices</description>

	<modules>
		<module>eureka-server</module>
		<module>api-gateway</module>
		<module>inventory-service</module>
		<module>request-issue-service</module>
		<module>notification-report-service</module>
		<module>auth-service</module>
		<module>donor-camp-service</module>
	</modules>

	<properties>
		<java.version>17</java.version>
		<spring-boot.version>3.2.5</spring-boot.version>
		<spring-cloud.version>2023.0.1</spring-cloud.version>
	</properties>

</project>
