server.port=${PORT:8085}
spring.application.name=notification-report-service

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/bloodbank}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:bloodbank}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info

# Twilio Configuration
twilio.enabled=false
