server.port=${PORT:9090}
spring.application.name=api-gateway

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[5]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.routes[0].id=inventory-service
spring.cloud.gateway.routes[0].uri=${INVENTORY_SERVICE_URL:lb://inventory-service}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/inventory-service/**, /api/inventory/**

spring.cloud.gateway.routes[1].id=request-issue-service
spring.cloud.gateway.routes[1].uri=${REQUEST_SERVICE_URL:lb://request-issue-service}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/request-issue-service/**, /api/request-issue/**

spring.cloud.gateway.routes[2].id=notification-report-service
spring.cloud.gateway.routes[2].uri=${NOTIFICATION_SERVICE_URL:lb://notification-report-service}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notification-report-service/**, /api/reports/**

spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=${AUTH_SERVICE_URL:lb://AUTH-SERVICE}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth-service/**, /api/auth/**

spring.cloud.gateway.routes[4].id=donor-camp-service
spring.cloud.gateway.routes[4].uri=${DONOR_SERVICE_URL:lb://DONOR-CAMP-SERVICE}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/donor-camp-service/**, /api/camps/**, /api/donors/**

management.endpoints.web.exposure.include=gateway,health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/}
